name: Wails build

on: [push, pull_request]

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'ConversorScanParaOCR'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'ConversorScanParaOCR'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'ConversorScanParaOCR'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Ubuntu Dependecies
        if: matrix.build.os == 'ubuntu-latest'
        run: |
          sudo apt install libasound2-dev

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.21.6'
